-- AlterEnum
ALTER TYPE "NotificationType" ADD VALUE IF NOT EXISTS 'SPECTATOR_BET_WON';
ALTER TYPE "NotificationType" ADD VALUE IF NOT EXISTS 'SPECTATOR_BET_LOST';
ALTER TYPE "NotificationType" ADD VALUE IF NOT EXISTS 'SPECTATOR_BET_REFUNDED';
