-- User notification mute
ALTER TABLE "User" ADD COLUMN IF NOT EXISTS "notificationsMuted" BOOLEAN NOT NULL DEFAULT false;

-- NotificationType additions
ALTER TYPE "NotificationType" ADD VALUE IF NOT EXISTS 'DEPOSIT_REQUESTED';
ALTER TYPE "NotificationType" ADD VALUE IF NOT EXISTS 'DEPOSIT_SUBMITTED';
ALTER TYPE "NotificationType" ADD VALUE IF NOT EXISTS 'WITHDRAWAL_SUBMITTED';
ALTER TYPE "NotificationType" ADD VALUE IF NOT EXISTS 'ADMIN_BALANCE_ADJUSTMENT';
ALTER TYPE "NotificationType" ADD VALUE IF NOT EXISTS 'WALLET_FROZEN';
ALTER TYPE "NotificationType" ADD VALUE IF NOT EXISTS 'WALLET_UNFROZEN';
ALTER TYPE "NotificationType" ADD VALUE IF NOT EXISTS 'ACCOUNT_SUSPENDED';
ALTER TYPE "NotificationType" ADD VALUE IF NOT EXISTS 'ACCOUNT_UNSUSPENDED';
